analyze olo_base_pkg_attribute.vhd
analyze olo_base_pkg_array.vhd
analyze olo_base_pkg_math.vhd
analyze olo_base_pkg_logic.vhd
analyze olo_axi_pkg_protocol.vhd
analyze olo_base_pkg_string.vhd

analyze olo_axi_lite_slave.vhd
analyze olo_axi_lite_slave_wrapper.vhd
