analyze axi_stream_frame_gen.vhd
analyze axi_stream_fifo.vhd
analyze axi_stream_delta.vhd
analyze axi4_lite/axi_lite_slave.vhd
analyze axi4_lite/axi_lite_ram_wrapper.vhd
analyze image_inversion.vhd

analyze axi4_lite_stream/axi_lite_slave.vhd
analyze axi4_lite_stream/axi_lite_ram_wrapper.vhd
analyze axi4_lite_stream/image_inversion.vhd